server:
  port: 4433
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: vmfhwprxm
    key-alias: spring

spring:
  cloud:
    gateway:
      routes:
        - id: member-server
          uri: https://stage41.xyz:40001
          predicates:
            - Path=/travel/member/**
          filters:
            - RewritePath=/travel/(?<path>.*),/$\{path}
            - name: JwtAuth
              args:
                excludePaths: /member
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    root: debug
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

auth-server:
  token_key:
    url: https://stage41.xyz:42222/oauth/token_key
